name: autofix.ci # needed to securely identify the workflow

on:
  push:
    branches:
      - main
    paths:
      - '/scripts/**/*'
      - '/src/**/*'
      - '/test/**/*'
      - '*'

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: install dependencies
        run: pnpm install
      - name: lint commit messages
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Checkout pull request branch (if PR branch)
        if: github.event_name == 'pull_request'
        run: git checkout ${{ github.event.pull_request.head.ref }}
      - name: lint commit messages (pr)
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: lint and format code
        run: pnpm run lint
      - name: commit autofix changes
        run: |
          git config --local user.name "Autofix Bot"
          git config --global user.email 'schapka@users.noreply.github.com'
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "no changes"
            exit 0
          fi
          git commit -m "chore: format"
          git push
